# Diezel Cryptofeed

# Local Spring Boot Configuration
spring:
  profiles:
    active: local   # For local machine execution configuration.

  # Security
  security:
    basic:
      enabled: false

  # Application Information
  application:
    name: Diezel Cryptofeed

  # Database
  datasource:
    # H2
    url: "jdbc:h2:file:~/testDB"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"

    # MySQL
    #url: jdbc:mysql://localhost/test              # Connection String
    #username: dbuser                              # Database Application account with full permissions
    #password: dbpass
    #driver-class-name: com.mysql.jdbc.Driver

  h2:
    console:
      enabled: true
      path: "/h2"

  jpa:
    hibernate:
      ddl-auto: "update"    # none, update, create, create-drop
    show-sql: true       # Logs SQL as its executed by JPA. Set org.hibernate logging level to INFO.

# Application Endpoint
server:
  port: 4150

# Flyway Database Migration Scripting
#flyway:
  #enabled: false      # Disable to avoid schema validation and/or auto-update every execution
  #url: X              # Database connection String
  #user: X             # Database user account with full permissions
  #password: X
  #placeholders:
    #db_schema: X
    #app_schema: X
    #data_tablespace: X

# Proxy
#proxy:
  #host: X
  #port: X

# Logging
logging:
  # Change Output Format
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"
  # Set Varying Log Levels Depending on Namespace
  level:
    com.diezel: ALL
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.netflix: DEBUG
  #file: "C:\diezel\cryptofeedlogs\diezel.log"    # Log to disk

# Security
management:
  security:
    enabled: false      # Disable to access actuator endpoints without requiring authentication.

# ---- Application-Properties Below ----
cryptofeed:
  security:
    enabled: false
    jwtSigningKey: "TEST123ABC123"
    admin:
      enableAdminUser: true
      adminUsername: "cryptofeed"
      adminPassword: "admin"
  vendor:
    kraken:
      baseUrl: "https://api.kraken.com"
      apiVersion: "0"
      apiKey: "XYZ"
      apiSecretKey: "XYZ"
    pushbullet:
      baseUrl: "https://api.pushbullet.com"
      apiVersion: "0"
      apiKey: "XYZ"
      apiSecretKey: "XYZ"


---

# Cloud Profile Configuration

# Cloud
spring:
  profiles: production   # Overwrite some local config values when hosted live in production environment.

  # Database
  jpa:
    properties:
      hibernate:
        ddl-auto: validate    # Validate schema, do not make changes.
  h2:
    console:
      enabled: true
      path: "/h2"

  management:
    security:
      enabled: true